### ISSUE TITLE
Popular a HomePage

### ISSUE THREAD

**Issue by HelmuthMN** [HelmuthMN/donat-front#6]
Arrumar a homepage, retornando dados da API, juntamente com as features novas que serão colocadas nela.

**Comment by Mfrzero** [comment]
Populado homepage. Necessita inserir imagens e textos.

**Comment by HelmuthMN** [comment]
Feito integração com banco de dados para retornar instituições randomicamente na home page. Arrumado uma das divs, com alguns links novos, como o de suporte ao projeto
